# This file tells Kubernetes to run Traefik with two replicas, expose it through a STACKIT Load Balancer using a public IP, 
# create a Traefik IngressClass,
# and make Traefik watch Kubernetes Ingress resources so external requests can be routed to services like your Go API.

# Run two controller Pods for availability.
deployment:
  replicas: 2

# Expose Traefik through the STACKIT Load Balancer.
service:
  type: LoadBalancer
  annotations:
    lb.stackit.cloud/external-address: "188.34.81.241"

# Create the Kubernetes IngressClass.
ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik

# Watch normal Kubernetes Ingress resources.
providers:
  kubernetesIngress:
    enabled: true

# Redirect all HTTP traffic to HTTPS.
ports:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true